name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target ./package --upgrade
      - name: Zip the site packages
        run: zip -r9 ${{ secrets.LAMBDA_ZIP_FILE }}.zip package/
      - name: Add lambda function to zipped file
        run: zip -g ${{ secrets.LAMBDA_ZIP_FILE }}.zip main.py
      - name: deploy to aws-lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: SlackJobNotifier
          zip_file: ${{ secrets.LAMBDA_ZIP_FILE}}.zip
